INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Daryl', 'Fauguel', 1, 8);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Arda', 'Allibone', 1, 11);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Durante', 'Ninnoli', 3, 3);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Jard', 'Twigger', 1, 3);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Tiebold', 'Voice', 2);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Caitrin', 'Osmar', 1);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Violetta', 'Condy', 2);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Iona', 'Jiroutek', 1);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Scarlett', 'Maleney', 1);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Vladimir', 'Nother', 1);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Thekla', 'Budgeon', 1);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Filmer', 'Tomkin', 3);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Jeno', 'McCrillis', 2);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Tina', 'Bauser', 1);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Samuele', 'Turbefield', 1, 5);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Glenn', 'Dimitru', 3, 4);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Pammie', 'Croxley', 2, 4);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Lita', 'Claughton', 1);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Ammamaria', 'Ennew', 2);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Ingmar', 'Badder', 2, 1);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Olive', 'Mottley', 3, 6);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Alasdair', 'Checcuzzi', 2);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Chantalle', 'Bertwistle', 1);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Billy', 'Hawtry', 1, 6);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Benoit', 'Fowls', 2, 6);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Thekla', 'Wilcock', 2, 4);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Brandi', 'Witherow', 3, 3);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Hanni', 'Verrico', 2);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Branden', 'Meegin', 3);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Bone', 'West', 2);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Garrek', 'Lockhart', 3);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Hugues', 'Catlin', 1, 4);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Marmaduke', 'Manicom', 1);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Titus', 'Lawson', 3, 4);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Othelia', 'Frondt', 3);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Loella', 'Randles', 1, 5);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Sybilla', 'Sawkin', 2, 9);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Vannie', 'Chubb', 2, 2);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Melanie', 'Bottom', 3);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Marga', 'Seymer', 2, 6);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Fairlie', 'Lorrie', 3);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Penni', 'Cardenoso', 3);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Felipa', 'Woodfield', 1);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Chrotoem', 'Sherrock', 1, 9);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Beauregard', 'Pirozzi', 3);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Akim', 'Risso', 1, 5);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Carie', 'Grigolon', 3, 4);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Gracie', 'Lorie', 1);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Eduardo', 'Moxstead', 2);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Gale', 'Wisniewski', 2);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Hastie', 'Pinel', 2);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Dorri', 'Roelvink', 1);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Shermie', 'Devall', 2, 5);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Whittaker', 'Tatford', 2, 3);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Shamus', 'Duinbleton', 1, 2);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante", "Stipendio_Orario") VALUES ('Auberta', 'Scholes', 3, 7);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Chance', 'Tolomei', 3);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Job', 'Waterstone', 3);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Sigismond', 'Parkman', 1);
INSERT INTO "Cameriere" ("Nome", "Cognome", "ID_Ristorante") VALUES ('Jourdan', 'Simanenko', 3);
